
#ifndef CONFIG_H
#define CONFIG_H

// RGB -> GRAY
#define WEIGHTED_AVERAGE 0
#define SIMPLE_AVERAGE 1
#define LUMINOSITY 2
#define GRAYSCALE_METHOD LUMINOSITY

#define BRIGHTEN_FIXED 0
#define BRIGHTEN_PERCENT 1
// #define BRIGHTEN_AMOUNT 150
#define BRIGHTEN_AMOUNT 0.7
#define BRIGHTNESS_METHOD BRIGHTEN_PERCENT

#define MAX_LINES 4000

#endif // CONFIG_H

